name: Cleanup old workflow runs
on:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt install gh jq

      - name: Delete old workflow runs except master branch

        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

          # Get workflow ID by name
          WORKFLOW_ID=$(gh workflow list --limit 100 | grep "Ubuntu test build" | awk '{print $NF}')

          # Get last 100 runs for this workflow
          gh run list --workflow="$WORKFLOW_ID" --limit 100 --json databaseId,headBranch | jq -c '.[]' |
          tail -n +11 | while read -r run; do
            ID=$(echo "$run" | jq -r '.databaseId')
            BRANCH=$(echo "$run" | jq -r '.headBranch')
            
            # Only delete if NOT from master branch
            if [ "$BRANCH" != "master" ]; then
              echo "Deleting run $ID on branch $BRANCH"
              gh run delete "$ID" -y
            else
              echo "Skipping run $ID on master"
            fi
          done
