name: Ubuntu test build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
 
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          qt6-base-dev \
          qt6-tools-dev \
          qt6-tools-dev-tools \
          qt6-serialport-dev \
          libhidapi-dev \
          libhidapi-hidraw0 \
          cmake \
          build-essential \
          zsync

    - name: Configure and Build
      working-directory: ${{github.workspace}}/
      run: ./compile.sh appimg

    - name: Test
      working-directory: ${{github.workspace}}/
      run: ./compile.sh ctest

