name: Ubuntu test build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
 
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          qt6-base-dev \
          qt6-tools-dev \
          qt6-tools-dev-tools \
          qt6-serialport-dev \
          libhidapi-dev \
          libhidapi-hidraw0 \
          cmake \
          build-essential \
          zsync \
          libxkbcommon-x11-dev

    - name: Configure and Build
      working-directory: ${{github.workspace}}/
      run: ./compile.sh appimage

    - name: Test
      working-directory: ${{github.workspace}}/
      run: ./compile.sh ctest

    - name: Upload AppImage artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: qtdmm-dev-build
        path: ${{ github.workspace }}/packages/QtDMM.AppImage
