name: macOS test build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install cmake qt@6 hidapi
        # Make Qt6 CMake config files discoverable
        echo "/opt/homebrew/opt/qt@6/bin" >> $GITHUB_PATH

    - name: Configure and Build
      working-directory: ${{github.workspace}}/
      run: ./compile.sh

    - name: Test
      working-directory: ${{github.workspace}}/
      run: ./compile.sh ctest
